### ISSUE TITLE
Production kW Watt division by 100 instead of 1000

### ISSUE THREAD

**Issue by mech78** [HarpunDK/Homey.Sonnen#2]
Hi,

https://github.com/HarpunDK/Homey.Sonnen/blob/77632c902abcb9ead4796f0d3cd4b4b75204c734/Source/com.sonnen.battery/drivers/sonnenbatterie/device.ts#L104

wrongly divides just by 100 instead of 1000:

 this.setCapabilityValue("production_capability", +latestStateJson.Production_W / 100);

**Comment by HarpunDK** [comment]
Ahh. New version is commited and submitted. 
Sorry for this.
