### ISSUE TITLE
v2/lastestdata.GridFeedIn_W (always) returns 0, but v2/status/GridFeedIn_W returns proper negative values

### ISSUE THREAD

**Issue by mech78** [HarpunDK/Homey.Sonnen#4]
Unfortunately the latestdata endpoint returns wrong readings for GridFeedIn_W. Seems to be zero all the time, despite one can see in the official apps that power is taken from the grid due to missing sunshine. The status endpoint however properly returns a negative value to indicate that.
Probably it's a bug in the sonnen api itself. However this means that the GridFeedIn_W is unusable and it needs to be changed to the other endpoing to get proper values.

In the past I had some own HTTP request based Homeyscript with device capabilities to create own "devices" and changed to /status for that reason. Not sure however what's the real difference between latestdata and status as both share many key-value pairs in common.

$ curl --header 'Auth-Token: ...' http://.../api/v2/latestdata | jq

 "Consumption_W": 1975,
  "FullChargeCapacity": 9765,
  "GridFeedIn_W": 0,
  "Pac_total_W": -2,
  "Production_W": 224,
  "RSOC": 8,
  "SetPoint_W": 0,
  "Timestamp": "2024-04-22 07:52:35",
  "USOC": 0,
  "UTC_Offet": 2,

$ curl --header 'Auth-Token: ...' http://.../api/v2/status | jq

{
  "Apparent_output": 90,
  "BackupBuffer": "0",
  "BatteryCharging": false,
  "BatteryDischarging": false,
  "Consumption_Avg": 2493,
  "Consumption_W": 2705,
  "Fac": 50.02199935913086,
  "FlowConsumptionBattery": false,
  "FlowConsumptionGrid": true,
  "FlowConsumptionProduction": true,
  "FlowGridBattery": false,
  "FlowProductionBattery": false,
  "FlowProductionGrid": false,
  "GridFeedIn_W": -2478,
  "IsSystemInstalled": 1,
  "OperatingMode": "2",
  "Pac_total_W": -3,
  "Production_W": 230,
  "RSOC": 8,
  "RemainingCapacity_Wh": 1693,

**Comment by HarpunDK** [comment]
Thank you for the great feedback provided.

New version is available here for test: https://homey.app/a/com.sonnen.battery/test/
Pushed new version for verification.

**Comment by HarpunDK** [comment]
Fixed in new version.
