### ISSUE TITLE
API Token

### ISSUE THREAD

**Issue by Smoody1207** [HarpunDK/Homey.Sonnen#6]
Where can i add an api token to charge the batterie manually for example?

**Comment by HarpunDK** [comment]
Hi @Smoody1207 

You will need to navigate to Settings + Sonnen Batterie > Configure (Mine is in danish, so guessing the english terms)
![image](https://github.com/HarpunDK/Homey.Sonnen/assets/8235893/0ef59295-e14d-4ca4-952c-8231647e2b02)
