### ISSUE TITLE
TOU startingtime as string does not take time label or stringvar as parameter

### ISSUE THREAD

**Issue by gitmiven** [HarpunDK/Homey.Sonnen#7]
I've tested the newly added funtionality TOU with startingtime as string. 

It works when entering the value as  string (eg 14:30) but not when using the time label or string variable with a corect formatted time string. It then returns error 400.

Somehow parameter passing is not correct.

![Screenshot_2024-09-22-15-32-34-12_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/user-attachments/assets/e15d8ff4-f3da-403d-bd59-95589d422669)

**Comment by gitmiven** [comment]
Hi Kim,

I did some extra testing and it seems Homey Logic has a bug where it adds a trailing whitespace to the tag values. So a correct time tag as "14:00" will be passed as "14:00 ". And this breaks the logic in the TOU functionality and gives status code 400. 

I would suggest to crop the time string to only use the 5 first letters, so "14:00 " will be cropped to "14:00". This way we can use the time tag values with or without trailing whitespace char.

**Comment by HarpunDK** [comment]
Hi @gitmiven , nice feedback. Just pushed version: 1.1.3

Trying to address this. Feel free to reopen if not solved.
