### ISSUE TITLE
Homey pro flow

### ISSUE THREAD

**Issue by AndersU1234** [HarpunDK/Homey.Sonnen#8]
Hello!
I cant get my flows to manage the battery.
I assume that a Homey flow will show up in Sonnen Buddy. But nothing happens. When testing a flow it looks good in Homey but the battery do not operate. When putting the commands in SB manually the battery works. Please help. Other flows works in Homey

**Comment by HarpunDK** [comment]
Hi  @AndersU1234, please ask the question here : https://community.homey.app/t/app-pro-sonnen-batterie/96052/56

Also provide screenshots and other relevant information.½

**Comment by HarpunDK** [comment]
See above comment.
