### ISSUE TITLE
Add SonnenBatterie through find-my.sonnen-batterie.com

### ISSUE THREAD

**Issue by bogguard** [HarpunDK/Homey.Sonnen#9]
Hello,

if you plan to keep maintaining this homey app, I'm gonna remove my app from the Homey store as it's way more useful for users to have only one.
Something I would recommend doing is adding the Sonnen Batterie only when it can be found on the local network.
Only the API key is needed in that case in the configuration
For this to work you can add the following to your onPairListDevices

```
async onPairListDevices() {
    try {
      const response = await axios.get(
        'https://find-my.sonnen-batterie.com/find'
      );

      if (response.data) {
        this.log('results found', response.data);
        const results = [];
        for (const e of response.data) {
          results.push({
            name: e.info,
            data: {
              id: e.device,
            },
            store: {
              lanip: e.lanip,
            },
          });
        }

        return results;
      }
    } catch (error) {
      console.error(error);
    }

    return [];
  }
```

It might happen that the IP of the batterie changes so it's good to listen to the errors of your API calls and have this fallback

```
this.log('failed to connect to Sonnen API', err);

          axios
            .get('https://find-my.sonnen-batterie.com/find')
            .then((res) => {
              if (res.data) {
                for (const e of res.data) {
                  if (this.getName() === e.info) {
                    this.log('found device and resetting', e.device, e.lanip);
                    this.setStoreValue('lanip', e.lanip);
                  }
                }
              }
            })
            .catch((err) => this.log('failed to find sonnen batteries', err));
        });
```

Your API calls can be renamed to `http://${this.getStore().lanip}:80/api/v2/...`

Let me know if you need help.

Kind regards,
Tim

**Comment by HarpunDK** [comment]
Hi @bogguard , I will check that out. As of now, the app (my implementation) only supports one device and is configured by the settings. I will look into it. Thank you for the input. 

Feel free to commit changes - the more the merrier.

**Comment by HarpunDK** [comment]
Added to the released version of Sonnen. Thank you for sharing.

**Comment by bogguard** [comment]
Thanks @HarpunDK .
Two things that you might need to update as it crashes my app.

In device.ts `this.getName()`shouldn't be called as it will go into error. Just replace it with this
```
console.log(
        'INVOKE',
        'LoadLatest...',
        'ERROR CATCH',
        retryOnError
      );
```

The widget doesn't work anymore as it calls the settings
`var baseUrl   = homey.settings.get("BatteryBaseUrl");`

**Comment by HarpunDK** [comment]
TY, I'm pushing an update now.
